# Generated by Django 6.0.6 on 2026-06-05 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('PageStart', models.IntegerField()),
                ('PageEnd', models.IntegerField()),
                ('IsColour', models.BooleanField(default=False)),
                ('Copies', models.IntegerField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('QueuedAt', models.DateTimeField(blank=True, null=True)),
                ('PrintedAt', models.DateTimeField(blank=True, null=True)),
                ('File', models.FileField(upload_to='orders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Fare', models.IntegerField()),
                ('token', models.CharField(max_length=255, unique=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
