# Generated by Django 6.0.6 on 2026-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderId', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('RazorpayPaymentId', models.CharField(max_length=255, unique=True)),
                ('RazorpayOrderId', models.CharField(max_length=255, unique=True)),
                ('RazorpaySignature', models.CharField(max_length=255, unique=True)),
                ('PaymentStatus', models.CharField(max_length=255)),
                ('PaidAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
