# Generated by Django 6.0.6 on 2026-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='RazorpaySignature',
            field=models.CharField(max_length=255),
        ),
    ]
